### ISSUE TITLE
Any chance we'll get audio modding features any time soon? #enhancement

### ISSUE THREAD

**Issue by Viambulance** [MattFiler/OpenCAGE#380] opened 2024-10-03 00:05 UTC

**Comment by MattFiler** [comment] 2024-10-03 08:41
Going to close this as a duplicate of #78 - support is planned at some point in the future, but I've been prioritising working on the tools that are bespoke to Alien: Isolation's engine for the time being, such as the script editor. The game uses Wwise for its sounds, so existing tools should work to import/export audio. 

I've also made the sound exporter previously which correctly re-names all sounds for you: https://github.com/MattFiler/Alien-Isolation-Audio-Extractor

**Closed by MattFiler** 2024-10-03 08:41 UTC
