### ISSUE TITLE
Commands editor *sometimes* closes without error message when creating VentTraverseMarker

### ISSUE THREAD

**Issue by ghramsey** [MattFiler/OpenCAGE#211] opened 2023-06-20 22:09 UTC
Tried to limit alien from dropping in a vent in Tech_hub from a specfic vent by deleting a VentTraverseMarker. 
Specificially this one: AYZ\LEVELS\SEVESTAPOL\TECHNICAL\LOBBY\TRANSITSTATION\TRANSITSTATION_SECTION\VentTraverseMarker_2

It crashed the game when alien tried to exit from there so I tried to undo by recreating the VentTraverseMarker entity I deleted.
Upon doing so the commands editor just closes when I use the create button.   It did three times then it worked when I used the name test instead of try to use the actual name.  The created  vent still crashes the game.  Probably related to some zone linkage  I broke 
with the deletion. I'll just revert to a previous save.      The editor silently closing though is an issue.

**Comment by MattFiler** [comment] 2023-07-09 11:25
To clarify, the entity was called `VentTraversalMarker_2`? I can't seem to replicate this 🤔

**Comment by ghramsey** [comment] 2023-07-09 20:13
Maybe it was something I broke while editing the map.  The vent is in Tech_Hub at the back wall where the first set of double doors lead to the 'boom room' on the right and systec lobby to the left. 

![image](https://github.com/MattFiler/OpenCAGE/assets/51859157/f6f416c2-aa1c-49d8-a438-d548c565e02f)

I'd put a collision barrier there to keep it from being used but the alien(s) spawn then just run blindly into the barrier 
and become stuck.  I was told try removing the venttraversalmarker instead which removes it as a place to drop from. 
The game crashed though when aliens tried to use it.  As soon as the tracker dot moved in that direction it just blooped 
to desktop.   I tried to restore the removed vent marker and the editor just crashed when it was trting to add the entity.  
It crashed twice and then the third time it didn't hence my description of "sometimes closes.." .   While it added it the venttraversalmarker no longer worked though.  It still crashed the game if the alien tried to use that vent.

I reverted that file so I don't have it anymore.  I wish now that I'd kept it.  
If you can't repro It was probably one time issue limited to something in that PAK file.

**Comment by MattFiler** [comment] 2023-07-12 17:55
I'm gonna close this as can't reproduce. If you encounter it again, please report it, but I've not been able to get this to happen :(

**Closed by MattFiler** 2023-07-12 17:55 UTC
Labels: bug, [TOOL] Script Editor
