### ISSUE TITLE
Coordinate marker discrepancy between Old and New Unity viewer in hospitalupper mission 5 story composite

### ISSUE THREAD

**Issue by ghramsey** [MattFiler/OpenCAGE#318] opened 2023-12-27 23:07 UTC
In discord I've posted about some trouble I've had spawning an android in the misssion story script for mission 5.
There's an offset which I've accounted for, but still the character is not being spawned in expected location or at all.
For completeness sake here's the message link: https://discord.com/channels/1116018062630592593/1116021579005038713/1189479038499172423

In talking with Darkstar he says to use Unity to locate the target entity and send those to the commands editor.
I did, but the character spawned in a different location than expected still.
He showed me a screenshot of Unity with coordinates in the Day Room. I used those numbers which work fine.  
He says he's using the old version of the Unity viewer before it connected with commands editor.
There seems to be a visual marker discrepency between his version of the level viewer and mine.

When I open Unity I'm seeing the same coordinates, but the marker is not the same as his;
![unity old_darkstar](https://github.com/MattFiler/OpenCAGE/assets/51859157/9d97cc49-b5e8-4bfe-bb48-e4e68bbe3fb0)
This first screenshot is what Darkstar sent in discord to help me locate the droid position.  The numbers on the right work fine.
The coordinate maker in the screenshot though is at issue;

![unity new](https://github.com/MattFiler/OpenCAGE/assets/51859157/4d210bb2-a0d1-434a-bc8d-b7131a1ef0f7)
This is what I get in Unity when I show the same coordinates.  The marker is in the air.

I've used the viewer to location some things like smoke bombs  in the level composites without issue.
Seems to be something quirky in this mission story composite.  

So is this just a setting I've got setup wrong in Unity?  Or what is going on?
The two markers are at odds given same coordinates for both.   Only difference is the different viewer version.

**Comment by MattFiler** [comment] 2023-12-28 09:22
The coordinates you see when you select something are relative to the parent they're contained within in the hierarchy on the left - make sure you're positioning things relative to the right parent.

I'm gonna close this issue as I suspect that's the cause, but if you still can't figure it out feel free to reopen and I'll take a look when I get chance.

**Closed by MattFiler** 2023-12-28 09:22 UTC
