### ISSUE TITLE
"Launch Game" button doesn't work

### ISSUE THREAD

**Issue by Const1702** [MattFiler/OpenCAGE#150] opened 2023-02-25 15:47 UTC
Right after the update the "Launch Game" button in the main OpenCAGE window doesn't open anything. I have it set to spawn me in "Tech_Comms" and I'm always spawning there. I can't switch it to another level, due to it not opening the launch game interface. Every other button I click on works.

_Noticed there is a new GitHub link button in the bottom right corner of the main window. Might be from that._

**OpenCAGE version: 0.9.3.51 (Staging)**

**Comment by MattFiler** [comment] 2023-02-25 15:49
Huh, weird. A couple questions:
- Are you using the Steam version?
- If you navigate to `/DATA/MODTOOLS/REMOTE_ASSETS/` please could you grab a screenshot of the contents of that folder?
Thanks!

**Comment by Const1702** [comment] 2023-02-25 15:51
I am using STEAM.
![image](https://user-images.githubusercontent.com/116276106/221366437-c86ea8e9-39dc-47df-9110-80055632326a.png)

**Comment by MattFiler** [comment] 2023-02-25 15:52
Is there anything in the `launchgame` folder?

**Comment by Const1702** [comment] 2023-02-25 15:53
Here is how it looks like:
![image](https://user-images.githubusercontent.com/116276106/221366534-a3377698-912f-40fb-9510-55d78154349a.png)

**Comment by Const1702** [comment] 2023-02-25 15:54
Just tried running it by double clicking on the .exe file with and without OpenCAGE running. No effect. It is probably opened in a special way by OCage.

**Comment by Const1702** [comment] 2023-02-25 16:22
**Here are the settings from the config file.** I tried to change "OPT_LoadToMap": "TECH_COMMS" to "FRONTEND" and other levels, but the changes seem to be applied only when I click on "Start Alien: Isolation" in the "Launch Game" window which doesn't show.
```
{
  "PATH_GameRoot": "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Alien Isolation",
  "META_GameVersion": "STEAM",
  "CONFIG_UseStagingBranch": true,
  "META_UniqueID": "59157D42CDC8BF2CD47354B864465B99049D12C0",
  "CONFIG_ShowPlatform": true,
  "OPT_LoadToMap": "TECH_COMMS",
  "UIOPT_PAUSEMENU": true,
  "OPT_CinematicTools": false,
  "UIOPT_NEWFRONTENDMENU": true,
  "UIOPT_LOADINGSCREEN": true,
  "UIOPT_GAMEOVERMENU": true,
  "CONFIG_RemoteBranch": "staging"
}
```

**Comment by MattFiler** [comment] 2023-02-25 16:37
If you run the LaunchGame.exe in that folder you screenshotted with the launch arg of `-opencage` followed by the path to your Alien: Isolation folder in quotes, does it open?

E.G. I made a `run.bat` file in the `launchgame` folder containing `LaunchGame -opencage "G:\SteamLibrary\steamapps\common\Alien Isolation"` and I could successfully launch it that way. 

Interested to see if you can.

**Comment by Const1702** [comment] 2023-02-25 16:47
Unfortunately it didn't work. Tried it with run (Win+R) and .bat file. Even as administrator. I only have windows defender. The cursor is showing a loading icon for a second which means it managed to run itself and tries to load something, but no window opens.

**Comment by MattFiler** [comment] 2023-02-25 16:47
Interesting! I'll have a dig.

**Comment by MattFiler** [comment] 2023-02-25 16:48
I assume the script editor is still working ok?

**Comment by Const1702** [comment] 2023-02-25 16:49
Yes. Every other button including the script editor works.

**Comment by MattFiler** [comment] 2023-02-25 17:33
Please could you try and put [this new exe](https://github.com/MattFiler/OpenCAGE/files/10831861/LaunchGame.zip) in the `launchgame` folder and paste the log.txt that gets generated here once you've tried opening "Launch Game" through OpenCAGE again. Thanks!

**Comment by Const1702** [comment] 2023-02-25 17:35
`init
paths set
location verified
LaunchGame()
enableCinematicTools: False
enableRuntimeUtils: False
`

**Comment by MattFiler** [comment] 2023-02-25 17:38
That's super useful, thanks! Please could you give [this one](https://github.com/MattFiler/OpenCAGE/files/10831868/LaunchGame.zip) a go? Should narrow down the cause of the issue!

**Comment by Const1702** [comment] 2023-02-25 17:47
Window opened! But the "Select level" is empty:
![image](https://user-images.githubusercontent.com/116276106/221371502-0cbeddf2-d85d-4e4a-b0c0-7b9c1265d890.png)

**Here is the new log:**

```init
paths set
location verified
LaunchGame()
enableCinematicTools: False
enableRuntimeUtils: False
init
paths set
location verified
LaunchGame()
enableCinematicTools: False
enableRuntimeUtils: False
1
2 -->
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\DATA\ENV\PRODUCTION'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at LaunchGame.LaunchGame..ctor(String MapToLaunchTo)
LaunchGame(): done
```
Clicking any button or checkbox gives an error (in this case when clicked Start Alien: Isolation, the message is a bit different with checkboxes):
![image](https://user-images.githubusercontent.com/116276106/221371584-94220363-450f-4bfc-9f1b-6f9f49e6fad1.png)

_Details:_
```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentOutOfRangeException: InvalidArgument=Value of '-1' is not valid for 'index'.
Parameter name: index
   at System.Windows.Forms.ComboBox.ObjectCollection.get_Item(Int32 index)
   at LaunchGame.LaunchGame.LaunchGame_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4614.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
LaunchGame
    Assembly Version: 0.1.0.0
    Win32 Version: 0.1.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Alien%20Isolation/DATA/MODTOOLS/REMOTE_ASSETS/launchgame/LaunchGame.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4550.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4605.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4605.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 13.0.2.27524
    CodeBase: file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Alien%20Isolation/DATA/MODTOOLS/REMOTE_ASSETS/launchgame/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
CathodeLib
    Assembly Version: 0.4.0.0
    Win32 Version: 0.4.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Alien%20Isolation/DATA/MODTOOLS/REMOTE_ASSETS/launchgame/CathodeLib.DLL
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```







Here is when I clicked on the "Add Quit to Menu On Death" checkbox (same error shows with other checkboxes).
![image](https://user-images.githubusercontent.com/116276106/221371655-35049c01-5be2-4d13-afd7-7e9061087d86.png)

_Details:_
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\DATA\UI.PAK'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.OpenWrite(String path)
   at CATHODE.PAK2.SaveInternal()
   at CathodeLib.CathodeFile.Save()
   at LaunchGame.LaunchGame.UpdateUI(String file, Boolean modded)
   at LaunchGame.LaunchGame.UIMOD_ReturnFrontend_CheckedChanged(Object sender, EventArgs e)
   at System.Windows.Forms.CheckBox.OnCheckedChanged(EventArgs e)
   at System.Windows.Forms.CheckBox.set_CheckState(CheckState value)
   at System.Windows.Forms.CheckBox.OnClick(EventArgs e)
   at System.Windows.Forms.CheckBox.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4614.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
LaunchGame
    Assembly Version: 0.1.0.0
    Win32 Version: 0.1.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Alien%20Isolation/DATA/MODTOOLS/REMOTE_ASSETS/launchgame/LaunchGame.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4550.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4605.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4605.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 13.0.2.27524
    CodeBase: file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Alien%20Isolation/DATA/MODTOOLS/REMOTE_ASSETS/launchgame/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
CathodeLib
    Assembly Version: 0.4.0.0
    Win32 Version: 0.4.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Steam/steamapps/common/Alien%20Isolation/DATA/MODTOOLS/REMOTE_ASSETS/launchgame/CathodeLib.DLL
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by MattFiler** [comment] 2023-02-25 17:48
Ayyy! Perfect, thanks - I see the issue. Will get an update out now.

**Comment by Const1702** [comment] 2023-02-25 17:50
I have a question. Why in the error it is showing 
![image](https://user-images.githubusercontent.com/116276106/221371878-6c640267-4e2c-4d8c-9065-8befd796bbb0.png)
It is supposed to be C:\Program Files (x86)\Steam\steamapps\common\Alien Isolation\DATA\ENV\PRODUCTION? Am I supposed to move files there or something or is it normal?

**Comment by MattFiler** [comment] 2023-02-25 17:53
Yeah it's an issue with setting the path to the game - could you give [this one](https://github.com/MattFiler/OpenCAGE/files/10831908/LaunchGame.zip) a go and see if it's fixed?

**Comment by Const1702** [comment] 2023-02-25 17:58
Still opens a broken "Launch Game" window:
![image](https://user-images.githubusercontent.com/116276106/221372343-4eb55f8a-9d6a-4790-9a18-f4b6ec689090.png)
![image](https://user-images.githubusercontent.com/116276106/221372347-a4844ae1-492a-4ece-9b1b-c3d8e2f87b9f.png)
![image](https://user-images.githubusercontent.com/116276106/221372360-5fbd9d89-a040-4170-abcf-db35866089ca.png)

**Here are the logs so far:**
```
init
paths set
location verified
LaunchGame()
enableCinematicTools: False
enableRuntimeUtils: False
init
paths set
location verified
LaunchGame()
enableCinematicTools: False
enableRuntimeUtils: False
1
2 -->
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\DATA\ENV\PRODUCTION'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at LaunchGame.LaunchGame..ctor(String MapToLaunchTo)
LaunchGame(): done
closing
init
paths set
location verified
LaunchGame()
enableCinematicTools: False
enableRuntimeUtils: False
1
2 -->
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\DATA\ENV\PRODUCTION'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at LaunchGame.LaunchGame..ctor(String MapToLaunchTo)
LaunchGame(): done
closing
init
paths set
init
paths set
location verified
LaunchGame()
enableCinematicTools: False
enableRuntimeUtils: False
1
2 -->
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\DATA\ENV\PRODUCTION'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at LaunchGame.LaunchGame..ctor(String MapToLaunchTo)
LaunchGame(): done
closing
init
paths set
location verified
LaunchGame()
enableCinematicTools: False
enableRuntimeUtils: False
1
2 -->
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\DATA\ENV\PRODUCTION'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at LaunchGame.LaunchGame..ctor(String MapToLaunchTo)
LaunchGame(): done

```

**Comment by MattFiler** [comment] 2023-02-25 18:04
Huh, interesting. Please could you try [this one](https://github.com/MattFiler/OpenCAGE/files/10831929/LaunchGame.zip) for me? Still won't work but the log might shed some more light on what is happening.

**Comment by Const1702** [comment] 2023-02-25 18:07
You are right it still doesn't work, **but here is the log:**
```
init
paths set
location verified
LaunchGame()
enableCinematicTools: False
enableRuntimeUtils: False
init
paths set
location verified
LaunchGame()
enableCinematicTools: False
enableRuntimeUtils: False
1
2 -->
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\DATA\ENV\PRODUCTION'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at LaunchGame.LaunchGame..ctor(String MapToLaunchTo)
LaunchGame(): done
closing
init
paths set
location verified
LaunchGame()
enableCinematicTools: False
enableRuntimeUtils: False
1
2 -->
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\DATA\ENV\PRODUCTION'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at LaunchGame.LaunchGame..ctor(String MapToLaunchTo)
LaunchGame(): done
closing
init
paths set
init
paths set
location verified
LaunchGame()
enableCinematicTools: False
enableRuntimeUtils: False
1
2 -->
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\DATA\ENV\PRODUCTION'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at LaunchGame.LaunchGame..ctor(String MapToLaunchTo)
LaunchGame(): done
closing
init
paths set
location verified
LaunchGame()
enableCinematicTools: False
enableRuntimeUtils: False
1
2 -->
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\DATA\ENV\PRODUCTION'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at LaunchGame.LaunchGame..ctor(String MapToLaunchTo)
LaunchGame(): done
closing
init
paths set
location verified
SharedData.pathToAI: C:\Program Files (x86)\Steam\steamapps\common\Alien Isolation
LaunchGame()
LaunchGame.SharedData.pathToAI: C:\Program Files (x86)\Steam\steamapps\common\Alien Isolation
_configPath: C:\Program Files (x86)\Steam\steamapps\common\Alien Isolation\OpenCAGE Settings.json
_jsonConfig: {
  "OPT_LoadToMap": "Frontend"
}
PATH_GameRoot: 
enableCinematicTools: False
enableRuntimeUtils: False
1
2 -->
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\DATA\ENV\PRODUCTION'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at LaunchGame.LaunchGame..ctor(String MapToLaunchTo)
LaunchGame(): done
```

**Comment by MattFiler** [comment] 2023-02-25 18:09
Ahhhhhh, I think I see the issue - do you not run OpenCAGE from your Alien: Isolation directory?

**Comment by Const1702** [comment] 2023-02-25 18:09
No. I run it in a seperate folder.

**Comment by MattFiler** [comment] 2023-02-25 18:10
Cool, that makes sense then - I'll try sort a fix! Thanks for all the help debugging :)

**Comment by Const1702** [comment] 2023-02-25 18:15
Something bizarre just happened. Turns out I had the OpenCAGE file in the Alien: Isolation folder as well, but I just haven't used it. I use the one from the seperate folder. Decided to try to open it from "Alien: Isolation" folder and got stuck in an update loop. Killed it with the task manager. Opened OpenCAGE back from where I usually do (the seperate folder) and the "Launch Game" window started opening properly, showing all levels and no errors.

**Comment by MattFiler** [comment] 2023-02-25 18:29
I've just pushed an update out to staging which should fix this issue. OpenCAGE now enforces that you launch it from A:I's directory (I thought I had already implemented this lol - hence the issues!).

If you prefer to keep OpenCAGE outside of A:I's directory for whatever reason, you should be able to right click and make a shortcut to OpenCAGE to continue opening it from the previous location.

Don't forget to copy your config json file with the exe :)

**Comment by MattFiler** [comment] 2023-02-25 18:30
> got stuck in an update loop
This will be to do with some update config changes I have made in the staging release - will be fixed once everything is merged down to main :)

**Closed** 2023-02-25 18:37 UTC
Labels: bug
