### ISSUE TITLE
Listed sound asset not present in game files

### ISSUE THREAD

**Issue by ghramsey** [MattFiler/OpenCAGE#180] opened 2023-04-13 16:02 UTC
Seems this sound object is not in the game folder A1_M1402_WAI_9622, but it's in the drop down list.
I thought it was only missing from the speechscript file, but it's absent from sound files too. 
Must be deleted material. 

For reference it's in ServerHubReception speech script. 
The dialog that preceeds it is A1_M1402_RIP_6752 so it's probably a response.
![image](https://user-images.githubusercontent.com/51859157/231818124-c3cc9bff-caff-4beb-84f8-0e20522c6778.png)
![image](https://user-images.githubusercontent.com/51859157/231818328-247aeb90-2683-405e-be0d-cd6f0a47e652.png)

It must exist somewhere since you have it in the list, but it's not present in my game folders.

**Comment by MattFiler** [comment] 2023-04-13 19:10
Good catch to find an unused bit of dialogue referenced by a SpeechScript! Looking at metadata files I have from other builds of the game, the sound's event is there (hence why I'm able to populate it in the dropdown), but the file reference in the Wwise project has been removed from the `Dialogue_M1402` soundbank, and it's also not in the subtitle files.

I've had a further poke into the metadata files & it seems this is actually quite common. M1402 especially seems to have quite a lot removed. I could probs make a thing to dump all the deleted names if you'd find it interesting.

Anyways, I'm gonna close this issue as it's not a bug with the tools as the sound event is still there 👍

**Closed by MattFiler** 2023-04-13 19:10 UTC
