### ISSUE TITLE
New rewire panel has blank interface

### ISSUE THREAD

**Issue by ghramsey** [MattFiler/OpenCAGE#181] opened 2023-04-13 21:48 UTC
![image](https://user-images.githubusercontent.com/51859157/231887123-7fd159e2-0a09-4d9f-9e14-3bf2a8a6d999.png)
![image](https://user-images.githubusercontent.com/51859157/231887170-914789a6-88da-402b-939f-6428f46192f8.png)

Trying to spawn a new rewire panel in Tech_Hub map.  
The zone is ServerHub and I spawned a save point successfully next to this as shown.    The location is in the by the upper lever 
in mission 10 where there is are steps up an a terminal in the corner.

The problem is the rewire panel always has a blank interface. 

I made proxies to the assets in UpperLobby for the rewire panels there sort of as a lark to see if I could.  
I can hear TAB button changing the room but the interface is unlit.

Is this related to #144 ?  Seems at least partially similar.

For all I know I've mucked up the entire thing, but I seem to remember having problems making a rewire panel in TecH_comms too. 
I ended up linking the new panel to the existing panels near the external comms panel.   In that instance it worked; I get nothing here but a blank face.

Also, the rewire box kept spawning in the floor when using the coordinates gathred from cheat engine . I had to offset them 
vertically by 5-6 points and the rotation is 180 degrees from that of the save stations.     This also happened with the panel I'd spawned in Tech _comms so that might be exclusive to the rewire panels.  Stil seems a bit odd though.

**Comment by ghramsey** [comment] 2023-04-13 23:07
Further. I tried merely cloning the rewire panel that turns on the gas in the server hub area. I believe it's the same zone.
Either way this cloned panel does same thing.  It's blank though I think I can hear interaction.

I may play with cloning it closer to the other panel to see if the clone is fault or it indeed just a different
 zone so I'd need a proxy.

**Comment by ghramsey** [comment] 2023-04-14 17:32
Cloning the panel produced initially a new box again at floor level (what is with the coordinates being offset?).  
I was able to access it but again blank panel. Attempts to move the original result in the entire thing just vanishing. 
 There are movers associated with the housing and door at least.  Trying to edit the movers on the door oddly 
 replaced the housing box back in it's original location, but just the housing.

What I found strange is that this is with the panel coordinates in the server_hub zone changed and the door mover changed it replaced only the bare housing object in the original location,   If these movers are all separate then it would be a nightmare 
to move each individual part until a graphic editor is in place or they are made able to be moved "intact".  
I won't be messing about with that for now.

Anywy, I reverted all of this and backed up the mover file before changing so as to not break anything.  

I'm back to square one though.  Still can't create a new, working rewire panel.

**Comment by Const1702** [comment] 2023-04-14 19:13
The problem is indeed like the one in #144. If you go to composite **AYZ\CONTROLS\REWIRESTANDALONE**. I managed to fix it with the following steps:
- Go to composite "AYZ\CONTROLS\REWIRESTANDALONE"
- There are two ModelReferences that you need to modify:

1. VDU_20_25cm04 (ModelReference)
- On its "resource" click "Edit Resource References" and a window should open
- In the Materials list there should be 1 material called "screenBlueTextScroll->InactiveScreen[000003]" (it is set like this by default by the game devs)
- Select it and click "Change Selected Material" and a window will open
- From there click on "screenBlueTextScroll->screen_anim_int_04" and click "Select This Material" then "Save All Changes"

2. VDU_20_25cm03 (ModelReference)
- In the Materials list there should be 1 material called "screenBlueTextScroll->InactiveScreen[000004]" (it is set like this by default by the game devs)
- Repeat the same steps and select the exact same material

**Comment by MattFiler** [comment] 2023-04-14 21:31
Cheers for the explanation @Const1702 - if this fixes the issue then I'll close it as we've got #144 to track the general issue :)

**Comment by ghramsey** [comment] 2023-04-15 00:58
Wow!!!  It works! I'm floored. 

Yeah.  I can see how zoning works to seemlessly load areas for resource saving.   Probably was for consoles since PCs 
even in 2014 had plenty of RAM to support the graphics.  Consoles though in 2014 were less robust to features like RAM 
and processing power.

Thank you again and many thanks!

**Comment by ghramsey** [comment] 2023-04-15 01:02
... oops! I closed it too soon.

Before I close this and since we're on this subject of rewire panel. 
Any theory as to why panel spawned is always offset vertically ?

When cheat engine shows X is say 20.  I had to set it to I think 26 to place it at eye level.
Is this difference amount able to be determined with any certainty ?

**Comment by MattFiler** [comment] 2023-04-15 09:06
You're placing it in the `SERVER_HUB` composite, which is offset by `0.00139425` in the Y when instanced within `ENVIRONMENT_TECHHUB` - perhaps it could be that?

**Comment by MattFiler** [comment] 2023-04-15 09:24
Just checked inside the actual REWIRE composite - the origin of the REWIRESTANDALONE composite within it (the actual model) is shifted down by -0.919 in the Y, could be that? You'll just need to account for the offset when placing them around :)

The SERVER_HUB composite is offset slightly when instanced within the ENVIRONMENT composite too, so your camera position through Cheat Engine or whatever will also be slightly out from the position the model will be being placed relative to the composite.

Random side note: while looking in the composite I noticed that the CMD_PlayAnimation for the rewire closing anim still exists (as seen in the original [dev diaries](https://youtu.be/xM0Fm1e0eTU?t=93)), they've just unhooked the start event on it - I assume it was removed to make constantly re-accessing the same point a bit quicker, but I believe doing this introduced the bug people sometimes get where you can get stuck at the exit stage 🤔

**Comment by ghramsey** [comment] 2023-04-15 16:57
Great.  That explains a bit.    Thanks once again.  

I'm still floored tht the missing rewire panel screen was solved so fast.

**Closed** 2023-04-16 16:07 UTC
Labels: question
